# Generated by Django 2.2.6 on 2019-10-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191007_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
