# Generated by Django 2.2.6 on 2019-10-08 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191008_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorder',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectable',
            name='desired_price',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='collectable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
