# Generated by Django 2.2.6 on 2019-10-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_collectable_ready_for_biddin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectable',
            old_name='ready_for_biddin',
            new_name='ready_for_bidding',
        ),
        migrations.AddField(
            model_name='bidorder',
            name='available',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='allow_bids', to='api.Collectable'),
            preserve_default=False,
        ),
    ]
