# Generated by Django 2.2.6 on 2019-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191009_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidorder',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
