# Generated by Django 2.2.6 on 2019-10-13 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191013_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectables', to=settings.AUTH_USER_MODEL),
        ),
    ]
